version: '3'

services:
  mssql-server-linux:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - mssql-server-linux-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=root
    ports:
      - "1433:1433"

volumes:
  mssql-server-linux-data:
