version: '3'

services:
  portainer-io:
    image: "portainer/portainer"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
      - "9000:9000"

volumes:
  portainer_data:
